---
- name: Create app folder 
  file:
    name: /opt/RebootRouter
    state: directory
    recurse: yes

- name: install virtualenv
  pip:
    executable: /usr/bin/pip3
    name: virtualenv
    state: latest

- name: create virtual env for app
  pip:
    virtualenv_python: /usr/bin/python3
    name: 
    - flask
    - celery
    - selenium
    - requests
    state: latest
    virtualenv: /opt/RebootRouter/appenv
