- name: Install command line tools
  become: true
  apt:
    name: 
    - kitty             # highly configurable terminal program
    - zoxide            # autojump replacement
    - exa               # rust based ls replacement
    - zsh               # fun to use shell
    - ripgrep           # rust based grep replacement
    - fd-find           # fust based find replacement
    - mosh              # ability to connect via slow links
    - snapd             # allows you to install snaps
    - ansible-lint      
    - tmux              # terminal multiplexer
    - npm
    - openssh-server    # ssh tools
    - iperf3            # add network testing tools
    state: present

- name: install snap's
  become: true
  community.general.snap:
    name:
      - core
      - starship

- name: remove blank .tmux.conf
  file:
    state: absent
    path: 
    - $HOME/.tmux.conf

- name: set shell to zsh
  become: true
  user:
    name: zach
    shell: /usr/bin/zsh

- name: clone repo for zsh-vi-mode 
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-vi-mode
    force: yes
    update: yes
      
- name: clone repo for zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    force: yes
    update: yes

- name: setup oh-my-zsh
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: zach
        oh_my_zsh:
          theme: robbyrussell
          plugins:
            - git
            - aws
            - history
            - sudo
            - web-search
            - copyfile
            - copybuffer
            - dirhistory
            - zsh-autosuggestions
            - zsh-vi-mode

- name: add custom items to .zshrc
  blockinfile:
    path: $HOME/.zshrc
    block: |
      ZVM_VI_INSERT_ESCAPE_BINDKEY=jj
      eval "$(starship init zsh)" 
      eval "$(zoxide init zsh)"
      alias exa='exa --group-directories-first'
      alias l='exa'
      alias la='exa -la'
      alias a='exa -a'
      alias ssh='kitty +kitten ssh'
      alias j='z'
      alias dot='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
      # find files changed in the .config directory in the last day 
      alias nf='fdfind . /home/zach/.config -H --changed-within 1d -E Code -E google-chrome -x /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME ls-files --others {} | sort | uniq'
      # git add files that changed in last day in .config
      alias nfa='fdfind . /home/zach/.config -H --changed-within 1d -E chromium -x /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME ls-files --others {} | uniq | rargs /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME add {0}'
    create: yes

- name: distribute private ssh keys
  copy:
    src: files/keys.enc
    dest: $HOME/.ssh/id_rsa
    owner: zach
    group: zach
    decrypt: yes
    mode: '0600'
  when: ansible_hostname == "mobile" 

- name: distribute ssh keys
  copy:
    src: files/pub
    dest: $HOME/.ssh/id_rsa.pub
    owner: zach
    group: zach
    mode: '0600'
  when: ansible_hostname == "mobile" 
