- name: Install command line tools
  become: true
  apt:
    name: 
    - kitty             # highly configurable terminal program
    - zoxide            # autojump replacement
    - exa               # rust based ls replacement
    - ripgrep           # rust based grep replacement
    - fd-find           # fust based find replacement
    - mosh              # ability to connect via slow links
    - snapd             # allows you to install snaps
    - ansible-lint      
    - tmux              # terminal multiplexer
    - npm
    - openssh-server    # ssh tools
    - iperf3            # add network testing tools
    state: present

- name: install snap's
  become: true
  community.general.snap:
    name:
      - core
      - starship

- name: remove blank .tmux.conf
  file:
    state: absent
    path: 
    - $HOME/.tmux.conf

- name: distribute private ssh keys
  copy:
    src: files/keys.enc
    dest: $HOME/.ssh/id_rsa
    owner: zach
    group: zach
    decrypt: yes
    mode: '0600'
  when: ansible_hostname == "mobile" 

- name: distribute ssh keys
  copy:
    src: files/pub
    dest: $HOME/.ssh/id_rsa.pub
    owner: zach
    group: zach
    mode: '0600'
  when: ansible_hostname == "mobile" 
