- name: ensure fonts directory
  file:
    path: $HOME/.fonts
    state: directory

- name: See if FiraCode exists
  stat:
    path: $HOME/.fonts/Fira\ Code\ Bold\ Nerd\ Font\ Complete.ttf
  register: fira_exists

- name: Download Fira Code
  when: not fira_exists.stat.exists
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip
    dest: "$HOME/.fonts/"
    remote_src: yes
 
- name: Install command line tools
  become: true
  apt:
    name: 
    - zsh               # fun to use shell
    state: present

- name: set shell to zsh
  become: true
  user:
    name: zach
    shell: /usr/bin/zsh

- name: setup oh-my-zsh
  include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: zach
        oh_my_zsh:
          theme: robbyrussell
          plugins:
            - git
            - aws
            - history
            - sudo
            - web-search
            - copyfile
            - copybuffer
            - dirhistory
            - zsh-autosuggestions
            - zsh-vi-mode
            - zsh-syntax-highlighting 

- name: clone repo for zsh-vi-mode 
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-vi-mode
    force: yes
    update: yes
      
- name: clone repo for zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    force: yes
    update: yes

- name: clone repo for zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    force: yes
    update: yes


- name: add custom items to .zshrc
  blockinfile:
    path: $HOME/.zshrc
    block: |
      source $HOME/.config/zsh/zshrc
