- name: download gpg key for github cli
    become: true
    get_url: 
      url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      dest: /etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg

- name: Add github apt source
    become: true
    apt_repository:
      repo: deb https://cli.github.com/packages stable main
      state: present
      validate_certs: true

- name: Install command line tools
  become: true
  apt:
    name: 
    - gh
    state: present

- name: setup git defaults
  include_role: 
    name: gantsign.git_user
  vars:
    users:
      - username: zach
        git_username: Zach Thieme
        git_user_email: zach@techsage.org
        git_user_force: yes

- name: add gh credentials
  shell: gh auth login --with-token 
  args:
    stdin: {{ github_pat }}
