- name: Install command line tools
  become: true
  apt:
    name: 
    - openjdk-8-jre-headless
    - rng-tools
    - unifi
    state: present

- name: update commandline.txt to support ethernet/usb
  become: true
  replace:
    path: /boot/cmdline.txt
    regexp: '^#HRNGDEVICE=/dev/hwrng'
    replace: 'HRNGDEVICE=/dev/hwrng'

