# - name: add folder for vim plug (vim plugin manager)
#   file:
#     path: $HOME/.local/share/nvim/site/autoload/
#     state: directory
#                         
# - name: install vim-plug
#   get_url:
#     url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     dest: $HOME/.local/share/nvim/site/autoload/plug.vim
#     force: yes

# - name: fix ownership that seems to drift to root
#   file:
#     path: $HOME/.local/share/nvim/site/autoload/plug.vim
#     recurse:
#     owner: zach
#     group: zach
- name: install packer 
  git:
    repo: https://github.com/wbthomason/packer.nvim 
    dest: $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
    force: yes
    update: yes
    depth: 1

- name: Install current stable neovim 
  become: true
  community.general.snap:
    name: nvim            # vim editor for the next age
    classic: yes
