---
- name: add local user Zach
  hosts: pi
  vars:
    sudoers:
      - zach
  remote_user: zach
  tasks:
    - name: create a 'wheel' group
      become: true
      group:
        name: wheel
        state: present

    - name: allow 'wheel' to have passwordless sudo
      become: true
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to wheel group
      become: true
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: " {{ sudoers }}"
