---
- name: adds bare git repo with my unix config 
  hosts: pi
  user: zach
  tasks:
    - name: remove blank .zshrc
      file:
        state: absent
        path: 
        - $HOME/.zshrc
        - $HOME/.tmux.conf

    - name: Check if .oh-my-zsh exists
      stat:
        path: $HOME/.oh-my-zsh
      register: stat_oh_my_zsh_result

    - name: Cloning  oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: $HOME/.oh-my-zsh
      when: not stat_oh_my_zsh_result.stat.exists

    - name: install zsh-vim plugin
      git:
        repo: https://github.com/jeffreytse/zsh-vi-mode
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-vi-mode 
        clone: yes
        update: yes
      when: stat_oh_my_zsh_result.stat.exists

    - name: ensure .cfg is in .gitignore
      lineinfile:
        path: $HOME/.gitignore
        regexp: '^\.cfg'
        line: .cfg

    - name: Clone config files
      git: 
        repo: https://github.com/zachthieme/config
        dest: $HOME/.cfg
        bare: yes

    - name: Check out config files 
      shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
      args:
        chdir: $HOME
        executable: /usr/bin/zsh

    - name: hide untracked files
      shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no 
      args:
        chdir: $HOME
        executable: /usr/bin/zsh
