---
- name: adds bare git repo with my unix config 
  hosts: pi
  user: zach
  tasks:
    - name: remove blank .tmux.conf
      file:
        state: absent
        path: 
        - $HOME/.tmux.conf

    - name: check if gitignore exists
      stat:
        path: $HOME/.gitignore
      register: stat_gitignore_result
      
    - name: create blank gitignore
      file:
        path: $HOME/.gitignore
        state: touch
      when: not stat_gitignore_result.stat.exists

    - name: ensure .cfg is in .gitignore
      lineinfile:
        path: $HOME/.gitignore
        regexp: '^\.cfg'
        line: .cfg

    - name: Clone config files
      git: 
        repo: https://github.com/zachthieme/config
        dest: $HOME/.cfg
        bare: yes
        update: yes

    - name: Check out config files 
      shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
      args:
        chdir: $HOME
        executable: /usr/bin/zsh

    - name: hide untracked files
      shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no 
      args:
        chdir: $HOME
        executable: /usr/bin/zsh
