---
- name: Install custome packages 
  hosts: pi
  remote_user: zach
  tasks:
    - name: Install neovim
      become: true
      apt:
        name: neovim
        state: present

    - name: Install autojump
      become: true
      apt:
        name: autojump
        state: present

    - name: Install code
      become: true
      apt:
        name: code
        state: present

    - name: Install mosh
      become: true
      apt:
        name: mosh
        state: present

    - name: install gh
      become: true
      apt:
        name: gh 
        state: present

    - name: install zsh-vim plugin
      git:
        repo: https://github.com/jeffreytse/zsh-vi-mode
        dest: $ZSH/custom/plugins/zsh-vi-mode 
        clone: yes
        update: yes
