---
- name: Install custom packages 
  hosts: k8
  remote_user: zach
  tasks:
    - name: Install apt packages 
      become: true
      apt:
        name: 
        - snap
        state: present

    - name: Enable container features
      become: true
      replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_enable=cpuset"
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
