---
- name: Install custom packages 
  hosts: mobile 
  remote_user: zach
  become: true
  tasks:
    - name: Install apt packages 
      apt:
        name: 
        - code
        - xmonad
        - xmobar
        - libghc-xmonad-contrib-dev
        - dnsmasq
        state: present

    - name: update /etc/modules 
      lineinfile:
        path: /etc/modules
        line: libcomposite

    - name: update dhcp settings 
      lineinfile:
        path: /etc/dhcpcd.conf
        line: denyinterfaces usb0 

    - name: update commandline.txt to support ethernet/usb
      replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "modules-load=dwc2,g_ether"

    - name: update config.txt
      lineinfile:
        path: /boot/config.txt
        line: dtoverlay=dwc2

    - name: add usb dnsmasq config
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: $HOME/.local/share/nvim/site/autoload/plug.vim
        force: ye

    - name: add usb interfact config 
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: $HOME/.local/share/nvim/site/autoload/plug.vim
        force: ye

    - name: add usb.sh
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: $HOME/.local/share/nvim/site/autoload/plug.vim
        force: ye
 
