---
- name: Install custom packages 
  hosts: mobile 
  remote_user: zach
  become: true
  tasks:
    - name: Install apt packages 
      apt:
        name: 
        - xrdp
        - code
        state: present

    - name: update commandline.txt to support ethernet/usb
      replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "modules-load=dwc2,g_ether"

    - name: update config.txt
      lineinfile:
        path: /boot/config.txt
        line: dtoverlay=dwc2
 
    - name: add xrdp user to ssl-cert
      user:
        name: xrdp
        groups: ssl-cert
        append: yes
