#TODO: install ZSH
#TODO: install PlugInstall
#TODO: delete .zshrc
#   - name: Remove file (delete file)
#     ansible.builtin.file:
#       path: /etc/foo.txt
#       state: absent

---
- import_playbook: piLocalUser.yml
- import_playbook: piWheel.yml
- import_playbook: piRemoveUser.yml
- import_playbook: piAptRepo.yml
- import_playbook: piSoftware.yml
- import_playbook: addConfigFiles.yml
