---
- name: Install custom packages 
  hosts: pi
  remote_user: zach
  tasks:
    - name: Install apt packages 
      become: true
      apt:
        name: 
        - neovim
        - zsh
        - autojump
        - code
        - mosh
        - gh
        - ansible
        - snapd
        - ansible-lint
        - tmux
        state: present
 
    - name: install snap's
      become: true
      community.general.snap:
        name:
          - core

    - name: add folder  for vim plug
      file:
        path: $HOME/.local/share/nvim/site/autoload/
        state: directory
          
    - name: install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: $HOME/.local/share/nvim/site/autoload/plug.vim
        force: yes

    - name: add gh credentials
      shell: gh auth login --with-token 
      args:
        stdin: "{{ github_pat }}"

    - name: set shell to zsh
      become: true
      user:
        name: zach
        shell: /bin/zsh
