---
- name: Install custom packages 
  hosts: pi
  remote_user: zach
  tasks:
    - name: Install apt packages 
      become: true
      apt:
        name: 
        - neovim
        - zsh
        - autojump
        - code
        - mosh
        - gh
        - ansible
        - ansible-lint
        state: present

    - name: install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: $HOME/.local/share/nvim/site/autoload/plug.vim
        force: yes

    - name: add gh credentials
      shell: gh auth login --with-token 
      args:
        stdin: "{{ github_pat }}"

    - name: set shell to zsh
      user:
        name: zach
        shell: /bin/zsh
    
