---
- name: Install custom packages 
  hosts: pi
  remote_user: zach
  become: true
  tasks:
    - name: Install apt packages 
      apt:
        name: 
        - neovim
        - autojump
        - code
        - mosh
        - gh
        state: present

    - name: install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/zach/.local/share/nvim/site/autoload/plug.vim

    - name: install zsh-vim plugin
      git:
        repo: https://github.com/jeffreytse/zsh-vi-mode
        dest: $ZSH/custom/plugins/zsh-vi-mode 
        clone: yes
        update: yes
        
    - name: add gh credentials
      shell:  gh auth login --with-token 
      args:
        stdin: "{{ github_pat }}"
