---
- name: create wheel group and add users
  hosts: pi
  become: true
  vars:
    sudoers:
      - zach
  remote_user: pi 
  tasks:
    - name: create a 'wheel' group
      group:
        name: wheel
        state: present

    - name: allow 'wheel' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: " {{ sudoers }}"
