___
- name: Setup virtualenv to run RebootRouter app
  hosts: pi
  user: zach
  become: yes
  tasks:
    - name: Create app folder 
      file:
        name: /opt/RebootRouter
        state: directory
        recurse: yes
    - name: install virtualenv
      pip:
        executable: /usr/bin/pip3
        name: virtualenv
        state: latest
    - name: create virtual env for app
      pip:
        executable: /usr/bin/pip3
        name: flask
        virtualenv: /opt/RebootRouter/appenv
