# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[|](bold blue)"

[hostname]
format = "[$hostname]($style)"

[username]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = false
style = " yellow"
format = "[:$path]($style)[$read_only]($read_only_style) "

