---

- hosts: all
  ignore_unreachable: yes
  roles: 
    - update
    - base
    - dotfiles
    - nvim

- hosts: test
  ignore_unreachable: yes
  roles: 
    - test

- hosts: radio
  ignore_unreachable: yes
  roles:
    - usbNetwork

- hosts: k8
  ignore_unreachable: yes
  become: true
  roles:
    - k8
    - disableWifi
    - docker

- hosts: pop
  ignore_unreachable: yes
  become: true
  roles:
    - pop
    - gitConfig
