---
all:
  hosts:
    pi-kub01:
      ansible_host: pi-kub01.theverse 
    pi-kub02:
      ansible_host: pi-kub02.theverse
    pi-kub03:
      ansible_host: pi-kub03.theverse
    pi-kub04:
      ansible_host: pi-kub04.theverse
    pi-kub05:
      ansible_host: pi-kub05.theverse
    pi-kub06:
      ansible_host: pi-kub06.theverse
  children:
    pi:
      hosts:
        pi-kub01: {}
        pi-kub02: {}
        pi-kub03: {}
        pi-kub04: {}
        pi-kub05: {}
        pi-kub06: {}
    k8:
      hosts:
        pi-kub01: {}
        pi-kub02: {}
        pi-kub03: {}
        pi-kub04: {}
        pi-kub05: {}
        pi-kub06: {}
  vars:
    ansible_python_interpreter: /usr/bin/python3
    remote_user: zach
