- name: download gpg key for github cli
  become: true
  get_url: 
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg

- name: Add github apt source
  become: true
  apt_repository:
    repo: deb https://cli.github.com/packages stable main
    state: present
    validate_certs: true

- name: download gpg key for unifi
  become: true
  get_url:
    url: https://dl.ui.com/unifi/unifi-repo.gpg 
    dest: /etc/apt/trusted.gpg.d/unifi-repo.gpg

- name: Add Unifi apt source
  become: true
  apt_repository:
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present
    validate_certs: true

- name: Install command line tools
  become: true
  apt:
    name: 
    - neovim
    - fish
    - autojump
    - mosh
    - gh
    - ansible
    - snapd
    - ansible-lint
    - tmux
    - npm
    state: present

- name: install snap's
  become: true
  community.general.snap:
    name:
      - core
      - starship

- name: add folder for vim plug (vim plugin manager)
  file:
    path: $HOME/.local/share/nvim/site/autoload/
    state: directory
      
- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: $HOME/.local/share/nvim/site/autoload/plug.vim
    force: yes

- name: set shell to fish
  become: true
  user:
    name: zach
    shell: /usr/bin/fish

- name: remove blank .tmux.conf
  file:
    state: absent
    path: 
    - $HOME/.tmux.conf

- name: enable password logins on ssh
    lineinfile:
      become: true
      path: /etc/ssh/sshd_config
      regexp: "^#PasswordAuthentication"
      line: PasswordAuthentication yes
      state: present
      backrefs: true
