- name: Enable container features
  replace:
    path: /boot/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"

- name: install snap
  package:
    name: snapd
    state: present 

- name: install k8 
  community.general.snap:
    name: microk8s
    classic: yes 

- name: install helm 
  community.general.snap:
    name: helm
    classic: yes 

- name: add zach to microk8s group
  user:
    name: zach
    groups: microk8s
    append: yes

- name: Install command line tools
  become: true
  apt:
    name: 
    - exa
    - neovim
    - exa
    - bat
    - ripgrep
    - fd-find
    - fish
    - autojump
    - mosh
    state: present
